name: Uwuify
version: '${project.version}'
main: ml.treecaptcha.uwuify.Uwuify
api-version: 1.18
authors: [ TreeCaptcha ]
description: made with stolen code from Ran-helo/uwu
website: http://treecaptcha.ml/
